### ISSUE TITLE
status command broken in dev branch

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#158]
Looks like the status command was not updated for the new fobs.json format:

```
$ cheetah.py status campaign -g all-methods-small -t -o
Traceback (most recent call last):
  File "/home/bda/.virtualenvs/codar/bin/cheetah.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bda/codar/cheetah/bin/cheetah.py", line 153, in <module>
    main()
  File "/home/bda/codar/cheetah/bin/cheetah.py", line 37, in main
    status_command(prog, command_args)
  File "/home/bda/codar/cheetah/bin/cheetah.py", line 149, in status_command
    show_parameters=args.show_parameters)
  File "/home/bda/codar/cheetah/codar/cheetah/status.py", line 46, in print_campaign_status
    code_names = _get_group_code_names(fob_file_path)
  File "/home/bda/codar/cheetah/codar/cheetah/status.py", line 93, in _get_group_code_names
    data = json.loads(line1)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
```

**Comment by kshitij-v-mehta** [comment]
Duplicate of #152 , it isn't in dev yet.

**Comment by kshitij-v-mehta** [comment]
I think I should merge the node-layout branch into dev, as it contains a couple of other fixes too. I wanted to test it more first, but merging it into dev should be fine.

**Comment by bd4** [comment]
ah ok, feel free to ignore my PR. Can we have some new tests for the stuff in the node-layout branch?

**Comment by bd4** [comment]
My philosophy is to try to have some unit tests and best effort for no bugs before merging into dev. so it might make sense to merge just my small fix and do more testing of node-layout before merging? Depends how close it is I guess.

**Comment by bd4** [comment]
duplicate #152
