### ISSUE TITLE
Cheetah workflow error `NameError: name 'pipeline' is not defined`

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#72]
Seeing the following error in `cedar.FOBrun.log` for a small test that finished in 5 seconds. Workflow does not run the remaining tests after this error occurs

```
2017-11-13 10:59:19,933:DEBUG:starting pipeline run-000, free nodes 8 -> 0
2017-11-13 10:59:19,948:INFO:run-000:heat start 3106 ['/sw/xk6/xalt/0.7.5/bin/aprun', '-n', '128', '-N', '16', '/lustre/atlas/proj-shared/csc143/kmehta/heat-transfer-codar-fork/heat_transfer_adios2', 'heat', '16', '8', '512', '512', '400', '1']
2017-11-13 10:59:30,831:INFO:run-000:heat done 3106 0
2017-11-13 10:59:30,833:ERROR:exception in Run thread
Traceback (most recent call last):
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 134, in run 
    self._run()
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 188, in _run
    callback(self)
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/consumer.py", line 101, in run_finished
    self.free_nodes + pipeline.get_nodes_used())
NameError: name 'pipeline' is not defined
2017-11-13 10:59:30,837:ERROR:exception in Run callbacks after Run thread exception
Traceback (most recent call last):
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 134, in run 
    self._run()
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 188, in _run
    callback(self)
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/consumer.py", line 101, in run_finished
    self.free_nodes + pipeline.get_nodes_used())
NameError: name 'pipeline' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 148, in run 
    callback(self)
  File "/lustre/atlas2/csc143/proj-shared/kmehta/cheetah/codar/workflow/model.py", line 377, in run_finished
    self._active_runs.remove(run)
KeyError: <Run(heat, started 139828067739392)>
2017-11-13 11:01:02,027:WARNING:killing all pipelines and exiting consumer
```

**Comment by bd4** [comment]
Sorry introduced that in logging commit, fixed by 23870d51248687645bcd2a3682b1df8d344eb510
